#!/usr/bin/env python3
"""
tests/05-e2e/run.py — Layer 5: end-to-end tests (SSO & friends).

Runs real user journeys over HTTP against a RUNNING stack (same convention
as 03-smoke, plus real credentials from .env):

  1. IdP (Zitadel)   — OIDC discovery + JWKS
  2. Portal          — landing page, /health, /api/services
  3. SSO login flow  — authorization-code + PKCE, logged in programmatically
                       through the Zitadel v2 Session API (the API the Login
                       v2 UI itself uses), using a throw-away OIDC app that
                       is bootstrapped (and removed) via the Management API
  4. Single sign-on  — a second authorize is finalized with the same IdP
                       session (no second credential check)
  5. Logout          — session termination; the dead session cannot
                       finalize further auth requests
  6. Apps            — reachability of running overlays (cloud, matrix,
                       notes, paperless)
  7. Synapse SSO     — /login/sso/redirect bounces to the IdP

No browser is involved: the login client PAT (IAM_LOGIN_CLIENT role, seeded
by `zitadel setup --steps /steps.yaml` into /machinekey/login-client.pat)
authorizes session creation, password checks and auth-request finalization.

Configuration precedence: env vars > .env > defaults. Relevant keys:
  OPENSME_DOMAIN, ZITADEL_DOMAIN, PORTAL_DOMAIN, OPENCLOUD_DOMAIN
  ZITADEL_ADMIN_PASSWORD            (demo: generated by scripts/demo.sh)
  E2E_ZITADEL_LOGIN_NAME            (default: zitadel-admin)
  E2E_ZITADEL_PAT                   machine-user PAT (skips docker compose cp)
  E2E_ZITADEL_LOGINCLIENT_PAT       login-client PAT (skips docker compose cp)
  E2E_OIDC_CLIENT_ID / _SECRET      pre-registered app (skips bootstrap)
  E2E_INSECURE=1                    force TLS verification off

Local demo domains (*.local) get two conveniences automatically:
  - unresolvable hostnames resolve to loopback (reaches local Traefik)
  - TLS verification is disabled (self-signed demo certs)

Usage:
  python3 tests/05-e2e/run.py                  # domain from .env / localhost
  python3 tests/05-e2e/run.py opensme.local
  make e2e DOMAIN=opensme.org

Exit codes: 0 = pass, 1 = one or more checks failed (skips don't fail).
"""

import argparse
import base64
import hashlib
import io
import os
import re
import secrets
import socket
import subprocess
import sys
import tarfile
from pathlib import Path
from urllib.parse import parse_qs, urlencode, urlparse

import requests
import urllib3

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from conftest import ROOT, Result

T = 15  # per-request timeout (s)
REDIRECTS = (301, 302, 303, 307, 308)
LOCALISH_SUFFIXES = (".local", ".localhost", ".test", ".invalid")
LOGIN_CLIENT_USER = "opensme-login-client"

VERIFY = True


class E2EError(Exception):
    """A flow-level failure (vs. infrastructure skip)."""


# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────

def load_env_file() -> dict:
    """Parse ROOT/.env (if present) into a flat dict."""
    data = {}
    env_path = ROOT / ".env"
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            data[k.strip()] = v.strip().strip('"').strip("'")
    return data


def is_localish(domain: str) -> bool:
    return domain in ("localhost", "127.0.0.1") or any(
        domain.endswith(s) for s in LOCALISH_SUFFIXES
    )


# ─────────────────────────────────────────────────────────────────────────────
# DNS fallback for local demo domains (no /etc/hosts edits needed)
# ─────────────────────────────────────────────────────────────────────────────

def install_dns_fallback() -> None:
    """Map hostnames that fail real DNS resolution to loopback.

    Local demo deployments route *.local hosts through Traefik on :80/:443;
    without an /etc/hosts entry those names don't resolve. Names that DO
    resolve are untouched, so this is inert against public domains.
    """
    original = socket.getaddrinfo

    def patched(host, *args, **kwargs):
        try:
            return original(host, *args, **kwargs)
        except socket.gaierror:
            if (
                isinstance(host, str)
                and re.fullmatch(r"[a-zA-Z0-9.-]+", host)
                and any(host.endswith(s) for s in LOCALISH_SUFFIXES)
            ):
                return original("127.0.0.1", *args, **kwargs)
            raise

    socket.getaddrinfo = patched


# ─────────────────────────────────────────────────────────────────────────────
# PKCE helpers
# ─────────────────────────────────────────────────────────────────────────────

def b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()


def make_pkce():
    verifier = b64url(secrets.token_bytes(48))
    challenge = b64url(hashlib.sha256(verifier.encode()).digest())
    return verifier, challenge


def authorize_url(disc, client_id, callback, scope="openid profile email"):
    verifier, challenge = make_pkce()
    state, nonce = secrets.token_urlsafe(16), secrets.token_urlsafe(16)
    qs = urlencode(
        {
            "client_id": client_id,
            "redirect_uri": callback,
            "response_type": "code",
            "scope": scope,
            "state": state,
            "nonce": nonce,
            "code_challenge": challenge,
            "code_challenge_method": "S256",
        }
    )
    return f"{disc['authorization_endpoint']}?{qs}", verifier, state


# ─────────────────────────────────────────────────────────────────────────────
# Seeded machine credentials (docker compose cp from the running zitadel)
# ─────────────────────────────────────────────────────────────────────────────

def fetch_seeded(container_path):
    """Read a seeded credential file from the running zitadel container.

    Tries the overlay set from $COMPOSE_FILE first, then the standard
    demo quartet (scripts/demo.sh), then base + idm — whatever defines a
    `zitadel` service wins. Returns the file content or None.
    """
    sets = []
    if os.environ.get("COMPOSE_FILE"):
        sets.append(os.environ["COMPOSE_FILE"].split(os.pathsep))
    sets.append([
        "docker-compose.yml",
        "idm/zitadel.yml",
        "opencloud/opencloud.yml",
        "profiles/demo.dev.yml",
    ])
    sets.append(["docker-compose.yml", "idm/zitadel.yml"])
    for files in sets:
        cmd = ["docker", "compose"]
        cmd += [arg for f in files for arg in ("-f", f)]
        if (ROOT / ".env").exists():
            cmd += ["--env-file", ".env"]
        cmd += ["cp", f"zitadel:{container_path}", "-"]
        try:
            r = subprocess.run(cmd, cwd=str(ROOT), capture_output=True, timeout=30)
        except Exception:
            continue
        if r.returncode != 0:
            continue
        try:
            tf = tarfile.open(fileobj=io.BytesIO(r.stdout))
            for member in tf.getmembers():
                if member.isfile():
                    return tf.extractfile(member).read().decode().strip()
        except tarfile.TarError:
            continue
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Zitadel Management API (machine PAT) — throw-away OIDC app bootstrap
# ─────────────────────────────────────────────────────────────────────────────

def mgmt(session, idp_base, pat, method, path, payload=None):
    return session.request(
        method,
        idp_base + path,
        json=payload if payload is not None else None,
        headers={"Authorization": f"Bearer {pat}"},
        timeout=T,
    )


def bootstrap_app(session, idp_base, pat, callback, post_logout):
    """Create (or reuse) a throw-away PKCE OIDC app. Returns (client_id, pid, app_id)."""
    proj_name = "e2e-sso"
    r = mgmt(session, idp_base, pat, "POST", "/management/v1/projects/_search", {})
    if r.status_code != 200:
        raise E2EError(f"project search failed: HTTP {r.status_code}")
    pid = next(
        (p["id"] for p in r.json().get("result", []) if p.get("name") == proj_name), None
    )
    if pid is None:
        r = mgmt(session, idp_base, pat, "POST", "/management/v1/projects",
                 {"name": proj_name})
        if r.status_code != 200:
            raise E2EError(f"project add failed: HTTP {r.status_code} {r.text[:120]}")
        pid = r.json().get("id")
    body = {
        "name": "e2e-sso",
        "redirectUris": [callback],
        "postLogoutRedirectUris": [post_logout],
        "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
        "grantTypes": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
        "appType": "OIDC_APP_TYPE_WEB",
        "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",  # public client, PKCE only
        "devMode": True,  # relax redirect-uri scheme checks (local domains)
    }
    r = mgmt(session, idp_base, pat, "POST",
             f"/management/v1/projects/{pid}/apps/oidc", body)
    if r.status_code != 200:
        raise E2EError(f"oidc app add failed: HTTP {r.status_code} {r.text[:120]}")
    data = r.json()
    return data.get("clientId"), pid, data.get("appId")


def cleanup_app(session, idp_base, pat, pid, app_id):
    if app_id:
        mgmt(session, idp_base, pat, "DELETE",
             f"/management/v1/projects/{pid}/apps/{app_id}")
    if pid:
        mgmt(session, idp_base, pat, "DELETE", f"/management/v1/projects/{pid}")


# ─────────────────────────────────────────────────────────────────────────────
# Zitadel v2 Session API — programmatic login (what the Login v2 UI does)
# ─────────────────────────────────────────────────────────────────────────────

def lc_headers(lc_pat, user_id):
    return {
        "Authorization": f"Bearer {lc_pat}",
        "x-zitadel-login-client": user_id,
    }


def resolve_user_id(session, idp_base, auth_value, login_name):
    """Find the userId for a login name (Management API user search; the
    v2 _by_login_name endpoint 404s until the login_names projection is
    fully warm). Matches machine users (bare name) and human users
    (org-domain suffixed name)."""
    r = session.post(
        f"{idp_base}/management/v1/users/_search",
        json={"userName": login_name.split("@")[0]},
        headers={"Authorization": f"Bearer {auth_value}"},
        timeout=T,
    )
    if r.status_code != 200:
        return None
    stem = login_name.split("@")[0].lower()
    for u in r.json().get("result", []):
        if str(u.get("userName", "")).lower().split("@")[0] == stem:
            return str(u.get("id"))
    return None


def api_login(session, idp_base, lc_pat, client_uid, authz_url, user_id, pw):
    """Log a user in via the v2 Session API and finalize the OIDC auth request.

    Returns (callback_query: dict, session: {id, token}).
    Raises E2EError on any non-2xx step.
    """
    h = lc_headers(lc_pat, client_uid)

    # (a) probe the authorize endpoint — expect a redirect to the login UI
    #     carrying the auth request id (do NOT follow it)
    r = session.get(authz_url, headers=h, allow_redirects=False, timeout=T)
    if r.status_code not in REDIRECTS or "Location" not in r.headers:
        raise E2EError(f"authorize probe: HTTP {r.status_code} {r.text[:80]}")
    m = re.search(r"authRequest=([A-Za-z0-9_:-]+)", r.headers["Location"])
    if not m:
        raise E2EError("authorize did not hand out an auth request id")
    req_id = m.group(1)

    # (b) create a session with the user check
    r = session.post(
        f"{idp_base}/v2/sessions",
        json={"checks": {"user": {"userId": user_id}}},
        headers=h, timeout=T,
    )
    if r.status_code >= 300:
        raise E2EError(f"session create: HTTP {r.status_code} {r.text[:80]}")
    j = r.json()
    sid, stok = j.get("sessionId"), j.get("sessionToken")
    if not sid or not stok:
        raise E2EError("session create returned no id/token")

    # (c) password check (returns the current session token)
    r = session.patch(
        f"{idp_base}/v2/sessions/{sid}",
        json={"checks": {"password": {"password": pw}}},
        headers=h, timeout=T,
    )
    if r.status_code >= 300:
        raise E2EError(
            f"password check: HTTP {r.status_code} "
            f"(wrong E2E_ZITADEL_LOGIN_NAME / ZITADEL_ADMIN_PASSWORD?)"
        )
    stok = r.json().get("sessionToken") or stok

    # (d) finalize the auth request with the session → callback URL
    qs = finalize(session, idp_base, lc_pat, client_uid, req_id, sid, stok)
    return qs, {"id": sid, "token": stok, "req": req_id}


def finalize(session, idp_base, lc_pat, client_uid, req_id, sid, stok):
    """Attach a session to an auth request; returns the callback query params."""
    r = session.post(
        f"{idp_base}/v2/oidc/auth_requests/{req_id}",
        json={"session": {"sessionId": sid, "sessionToken": stok}},
        headers=lc_headers(lc_pat, client_uid), timeout=T,
    )
    if r.status_code >= 300:
        raise E2EError(f"finalize auth request: HTTP {r.status_code} {r.text[:80]}")
    cb = r.json().get("callbackUrl", "")
    qs = parse_qs(urlparse(cb).query)
    if "code" not in qs:
        raise E2EError(f"callback without code: {sorted(qs)}")
    return qs


def terminate(session, idp_base, lc_pat, client_uid, sid, stok):
    """Terminate an IdP session (DELETE /v2/sessions/{id}, token in body)."""
    r = session.delete(
        f"{idp_base}/v2/sessions/{sid}",
        json={"sessionToken": stok},
        headers=lc_headers(lc_pat, client_uid), timeout=T,
    )
    return r.status_code < 300


# ─────────────────────────────────────────────────────────────────────────────
# Sections
# ─────────────────────────────────────────────────────────────────────────────

def probe(session, url) -> bool:
    try:
        session.get(url, timeout=5, allow_redirects=True)
        return True
    except requests.RequestException:
        return False


def section_discovery(result, session, idp_base):
    try:
        r = session.get(f"{idp_base}/.well-known/openid-configuration", timeout=T)
    except requests.RequestException as e:
        result.fail(f"IdP discovery unreachable: {e.__class__.__name__}")
        return None
    if r.status_code != 200:
        result.fail(f"openid-configuration: HTTP {r.status_code}")
        return None
    disc = r.json()
    missing = [
        k for k in ("issuer", "authorization_endpoint", "token_endpoint", "jwks_uri")
        if not disc.get(k)
    ]
    if missing:
        result.fail(f"discovery missing keys: {missing}")
        return None
    result.ok(f"OIDC discovery ok (issuer {disc['issuer']})")

    issuer_host = urlparse(disc["issuer"]).netloc
    if issuer_host and issuer_host != urlparse(idp_base).netloc:
        result.warn(f"issuer host {issuer_host} != configured host")
    try:
        jwks = session.get(disc["jwks_uri"], timeout=T)
        keys = len(jwks.json().get("keys", [])) if jwks.status_code == 200 else 0
        (result.ok if keys else result.fail)(f"JWKS: {keys} key(s)")
    except requests.RequestException:
        result.fail("JWKS unreachable")
    return disc


def section_portal(result, session, portal_base):
    try:
        r = session.get(portal_base + "/", timeout=T)
    except requests.RequestException:
        result.skip("portal unreachable")
        return
    if r.status_code != 200:
        result.fail(f"portal /: HTTP {r.status_code}")
    elif "openSME" not in r.text and "opensme" not in r.text.lower():
        result.fail("portal / does not mention openSME")
    else:
        result.ok("portal landing page ok")
    try:
        h = session.get(portal_base + "/health", timeout=T)
        ok = h.status_code == 200 and h.json().get("status") == "ok"
        (result.ok if ok else result.fail)(
            "portal /health ok" if ok else f"portal /health: HTTP {h.status_code} {h.text[:60]}"
        )
        s = session.get(portal_base + "/api/services", timeout=T)
        services = s.json().get("services") if s.status_code == 200 else None
        (result.ok if isinstance(services, list) else result.fail)(
            f"portal /api/services: {len(services)} service(s)" if isinstance(services, list)
            else f"portal /api/services: HTTP {s.status_code}"
        )
    except (requests.RequestException, ValueError) as e:
        result.fail(f"portal API: {e.__class__.__name__}")


def run_auth_code_flow(result, session, disc, client_id, csec, idp_base,
                       lc_pat, client_uid, login_name, login_uid, pw, callback):
    """Step 3: full authorization-code + PKCE round trip. Returns id_token + session."""
    authz, verifier, state = authorize_url(disc, client_id, callback)
    qs, sess = api_login(session, idp_base, lc_pat, client_uid, authz, login_uid, pw)
    if qs.get("state", [None])[0] != state:
        raise E2EError("state mismatch at callback")
    result.ok("login flow produced an authorization code")

    tok = session.post(
        disc["token_endpoint"],
        data={
            "grant_type": "authorization_code",
            "code": qs["code"][0],
            "redirect_uri": callback,
            "client_id": client_id,
            "code_verifier": verifier,
        },
        auth=(client_id, csec) if csec else None,
        timeout=T,
    )
    if tok.status_code != 200:
        raise E2EError(f"token endpoint: HTTP {tok.status_code} {tok.text[:120]}")
    body = tok.json()
    access = body.get("access_token")
    idt = body.get("id_token")
    if not access or not idt:
        raise E2EError("token response missing access/id tokens")
    if len(idt.split(".")) != 3:
        raise E2EError("id_token is not a JWS compact token")
    result.ok("PKCE token exchange ok")

    ui = session.get(
        disc.get("userinfo_endpoint", f"{idp_base}/oidc/v1/userinfo"),
        headers={"Authorization": f"Bearer {access}"},
        timeout=T,
    )
    if ui.status_code != 200:
        raise E2EError(f"userinfo: HTTP {ui.status_code}")
    preferred = ui.json().get("preferred_username", "")
    stem = login_name.split("@")[0]
    if stem.lower() not in str(preferred).lower():
        raise E2EError(f"userinfo subject {preferred!r} does not match {stem!r}")
    result.ok(f"userinfo authenticated as {preferred}")
    return idt, sess


def section_sso_reuse(result, session, disc, client_id, callback, idp_base,
                      lc_pat, client_uid, sess):
    """Step 4: a second authorize for the same user is finalized with the
    existing IdP session — no second password check anywhere."""
    authz, _, _ = authorize_url(disc, client_id, callback)
    h = lc_headers(lc_pat, client_uid)
    r = session.get(authz, headers=h, allow_redirects=False, timeout=T)
    if r.status_code not in REDIRECTS or "Location" not in r.headers:
        result.fail(f"single sign-on: authorize probe HTTP {r.status_code}")
        return False
    m = re.search(r"authRequest=([A-Za-z0-9_:-]+)", r.headers["Location"])
    if not m:
        result.fail("single sign-on: no auth request id")
        return False
    try:
        finalize(session, idp_base, lc_pat, client_uid, m.group(1), sess["id"], sess["token"])
        result.ok("single sign-on: existing IdP session authorized a second app")
        return True
    except E2EError as e:
        result.fail(f"single sign-on not working: {e}")
        return False


def section_logout(result, session, idp_base, lc_pat, client_uid, sess, client_id, callback, disc):
    """Step 5: terminate the IdP session; a fresh auth request can no longer
    be finalized with the dead session."""
    if not terminate(session, idp_base, lc_pat, client_uid, sess["id"], sess["token"]):
        result.fail("session termination API rejected the request")
        return
    authz, _, _ = authorize_url(disc, client_id, callback)
    h = lc_headers(lc_pat, client_uid)
    r = session.get(authz, headers=h, allow_redirects=False, timeout=T)
    m = re.search(r"authRequest=([A-Za-z0-9_:-]+)", r.headers.get("Location", ""))
    if not m:
        result.warn("logout check: could not open a fresh auth request")
        return
    try:
        finalize(session, idp_base, lc_pat, client_uid, m.group(1), sess["id"], sess["token"])
        result.fail("logout ineffective: dead session still finalizes auth requests")
    except E2EError:
        result.ok("logout: terminated session rejected by the IdP")


def section_apps(result, session, urls):
    for label, url in urls:
        try:
            r = session.get(url, timeout=T, allow_redirects=False)
            if r.status_code < 500:
                result.ok(f"{label}: HTTP {r.status_code}")
            else:
                result.fail(f"{label}: HTTP {r.status_code}")
        except requests.RequestException:
            result.skip(f"{label} not running")


def section_synapse_sso(result, session, matrix_base, idp_base):
    url = f"{matrix_base}/_matrix/client/v3/login/sso/redirect"
    try:
        r = session.get(
            url, params={"redirectUrl": matrix_base + "/"},
            allow_redirects=False, timeout=T,
        )
    except requests.RequestException:
        result.skip("synapse not running")
        return
    if r.status_code == 404:
        result.skip("synapse SSO not enabled (no OIDC provider wired)")
        return
    loc = r.headers.get("Location", "")
    if r.status_code in REDIRECTS and loc.startswith(idp_base):
        result.ok("synapse SSO redirect targets the IdP")
    elif r.status_code in REDIRECTS:
        result.fail(f"synapse SSO redirects to {loc[:80]} (expected the IdP)")
    else:
        result.warn(f"synapse SSO probe: HTTP {r.status_code}")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> bool:
    global VERIFY
    ap = argparse.ArgumentParser(description="openSME e2e tests (SSO etc.)")
    ap.add_argument("domain", nargs="?", default=None, help="stack domain")
    ap.add_argument("--insecure", action="store_true", help="disable TLS verification")
    ap.add_argument("--map-local", action="store_true",
                    help="resolve unresolvable *.local hosts to loopback")
    ap.add_argument("--skip-flows", action="store_true", help="skip SSO flow tests")
    ap.add_argument("--skip-apps", action="store_true", help="skip app reachability")
    ap.add_argument("--idp-url", default=None, help="override IdP base URL")
    args = ap.parse_args()

    dotenv = load_env_file()

    def cfg(key, default=""):
        return os.environ.get(key) or dotenv.get(key) or default

    domain = (args.domain or cfg("OPENSME_DOMAIN", "localhost")).strip()
    localish = is_localish(domain)
    VERIFY = not (args.insecure or cfg("E2E_INSECURE") in ("1", "true", "yes") or localish)
    if not VERIFY:
        urllib3.disable_warnings()
    if localish or args.map_local:
        install_dns_fallback()

    idp_host = cfg("ZITADEL_DOMAIN", f"auth.{domain}")
    idp_base = args.idp_url or f"https://{idp_host}"
    portal_base = (
        "http://127.0.0.1:8080" if domain in ("localhost", "127.0.0.1")
        else f"https://{cfg('PORTAL_DOMAIN', f'portal.{domain}')}"
    )
    cloud_base = f"https://{cfg('OPENCLOUD_DOMAIN', f'cloud.{domain}')}"
    matrix_base = f"https://matrix.{domain}"
    notes_base = f"https://notes.{domain}"
    paperless_base = f"https://paperless.{domain}"

    session = requests.Session()
    session.verify = VERIFY

    result = Result("e2e")
    result.header(f"openSME e2e — domain={domain} idp={idp_base} verify={VERIFY}")

    if not probe(session, idp_base + "/debug/ready") and not probe(session, portal_base + "/health"):
        result.fail("stack unreachable — start it first (./scripts/demo.sh or make up)")
        return result.summary()

    # 1) IdP discovery
    disc = section_discovery(result, session, idp_base)

    # 2) Portal
    section_portal(result, session, portal_base)

    # 3-5) SSO flows
    flows_ok = bool(disc) and not args.skip_flows
    client_id, csec, owned, pat = cfg("E2E_OIDC_CLIENT_ID"), cfg("E2E_OIDC_CLIENT_SECRET"), None, None
    callback, post_logout = f"{idp_base}/e2e-callback", f"{idp_base}/e2e-loggedout"
    login_name = cfg("E2E_ZITADEL_LOGIN_NAME", "zitadel-admin")
    pw = cfg("ZITADEL_ADMIN_PASSWORD")

    lc_pat = cfg("E2E_ZITADEL_LOGINCLIENT_PAT")
    client_uid = None

    if flows_ok and not client_id:
        pat = cfg("E2E_ZITADEL_PAT") or fetch_seeded("/machinekey/pat")
        if not pat:
            result.skip("SSO flows: no machine PAT reachable (docker compose down?) — "
                        "set E2E_OIDC_CLIENT_ID or E2E_ZITADEL_PAT")
            flows_ok = False
        else:
            try:
                client_id, pid, app_id = bootstrap_app(session, idp_base, pat, callback, post_logout)
                owned = (pid, app_id)
                result.ok(f"bootstrapped throw-away OIDC app (client {client_id})")
            except E2EError as e:
                result.skip(f"SSO flows skipped — OIDC app bootstrap failed: {e}")
                flows_ok = False

    if flows_ok:
        lc_pat = lc_pat or fetch_seeded("/machinekey/login-client.pat")
        client_uid = resolve_user_id(session, idp_base, pat or lc_pat, LOGIN_CLIENT_USER) \
            if lc_pat else None
        if not lc_pat or not client_uid:
            result.skip("SSO flows: no login-client PAT (re-run `zitadel setup --steps "
                        "/steps.yaml` on a fresh DB) or set E2E_ZITADEL_LOGINCLIENT_PAT")
            flows_ok = False

    login_uid = None
    if flows_ok:
        login_uid = resolve_user_id(session, idp_base, pat or lc_pat, login_name)
        if not login_uid:
            result.fail(f"auth-code flow: login user {login_name!r} not found in IdP")
            flows_ok = False

    if flows_ok and not pw:
        result.skip("SSO flows: no admin credentials (set ZITADEL_ADMIN_PASSWORD)")
        flows_ok = False

    sess = None
    if flows_ok:
        try:
            _, sess = run_auth_code_flow(
                result, session, disc, client_id, csec, idp_base,
                lc_pat, client_uid, login_name, login_uid, pw, callback,
            )
        except E2EError as e:
            result.fail(f"auth-code flow: {e}")
            flows_ok = False

    if flows_ok and sess:
        if section_sso_reuse(result, session, disc, client_id, callback, idp_base,
                             lc_pat, client_uid, sess):
            section_logout(result, session, idp_base, lc_pat, client_uid, sess,
                           client_id, callback, disc)

    # Cleanup the throw-away app (best effort)
    if owned and pat:
        try:
            cleanup_app(session, idp_base, pat, owned[0], owned[1])
            result.ok("removed throw-away OIDC app")
        except Exception:
            result.warn("could not remove throw-away OIDC app (delete project 'e2e-sso')")

    # 6) App reachability
    if not args.skip_apps:
        section_apps(result, session, [
            ("opencloud", cloud_base + "/"),
            ("synapse", matrix_base + "/_matrix/client/versions"),
            ("notes", notes_base + "/"),
            ("paperless", paperless_base + "/"),
        ])

    # 7) Synapse SSO wiring
    if not args.skip_apps:
        section_synapse_sso(result, session, matrix_base, idp_base)

    return result.summary()


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
