#!/usr/bin/env python3
"""
tests/05-e2e/run.py — Layer 5: end-to-end tests (SSO & friends).

Runs real user journeys over HTTP against a RUNNING stack (same convention
as 03-smoke, plus real credentials from .env):

  1. IdP (Zitadel)   — OIDC discovery + JWKS
  2. Portal          — landing page, /health, /api/services
  3. SSO login flow  — authorization-code + PKCE, logged in programmatically
                       through the Zitadel v2 Session API (the API the Login
                       v2 UI itself uses), using a throw-away OIDC app that
                       is bootstrapped (and removed) via the Management API
  4. Single sign-on  — a second authorize is finalized with the same IdP
                       session (no second credential check)
  5. Logout          — session termination; the dead session cannot
                       finalize further auth requests
  6. Apps            — reachability of running overlays (cloud, matrix,
                       notes, paperless)
  7. Synapse SSO     — /login/sso/redirect bounces to the IdP

No browser is involved: the login client PAT (IAM_LOGIN_CLIENT role, seeded
by `zitadel setup --steps /steps.yaml` into /machinekey/login-client.pat)
authorizes session creation, password checks and auth-request finalization.

Configuration precedence: env vars > .env > defaults. Relevant keys:
  OPENSME_DOMAIN, ZITADEL_DOMAIN, PORTAL_DOMAIN, OPENCLOUD_DOMAIN
  ZITADEL_ADMIN_PASSWORD            (demo: generated by scripts/demo.sh)
  E2E_ZITADEL_LOGIN_NAME            (default: zitadel-admin)
  E2E_ZITADEL_PAT                   machine-user PAT (skips docker compose cp)
  E2E_ZITADEL_LOGINCLIENT_PAT       login-client PAT (skips docker compose cp)
  E2E_OIDC_CLIENT_ID / _SECRET      pre-registered app (skips bootstrap)
  E2E_INSECURE=1                    force TLS verification off

Local demo domains (*.local) get two conveniences automatically:
  - unresolvable hostnames resolve to loopback (reaches local Traefik)
  - TLS verification is disabled (self-signed demo certs)

Usage:
  python3 tests/05-e2e/run.py                  # domain from .env / localhost
  python3 tests/05-e2e/run.py opensme.local
  make e2e DOMAIN=opensme.org

Exit codes: 0 = pass, 1 = one or more checks failed (skips don't fail).
"""

import argparse
import base64
import hashlib
import io
import json
import os
import re
import secrets
import socket
import subprocess
import sys
import tarfile
import time
from pathlib import Path
from urllib.parse import parse_qs, urlencode, urlparse

import requests
import urllib3

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from conftest import ROOT, Result

T = 15  # per-request timeout (s)
REDIRECTS = (301, 302, 303, 307, 308)
LOCALISH_SUFFIXES = (".local", ".localhost", ".test", ".invalid")
LOGIN_CLIENT_USER = "opensme-login-client"

VERIFY = True


class E2EError(Exception):
    """A flow-level failure (vs. infrastructure skip)."""


# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────

def load_env_file() -> dict:
    """Parse ROOT/.env (if present) into a flat dict."""
    data = {}
    env_path = ROOT / ".env"
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            data[k.strip()] = v.strip().strip('"').strip("'")
    return data


def is_localish(domain: str) -> bool:
    return domain in ("localhost", "127.0.0.1") or any(
        domain.endswith(s) for s in LOCALISH_SUFFIXES
    )


# ─────────────────────────────────────────────────────────────────────────────
# DNS fallback for local demo domains (no /etc/hosts edits needed)
# ─────────────────────────────────────────────────────────────────────────────

def install_dns_fallback() -> None:
    """Map hostnames that fail real DNS resolution to loopback.

    Local demo deployments route *.local hosts through Traefik on :80/:443;
    without an /etc/hosts entry those names don't resolve. Names that DO
    resolve are untouched, so this is inert against public domains.
    """
    original = socket.getaddrinfo

    def patched(host, *args, **kwargs):
        try:
            return original(host, *args, **kwargs)
        except socket.gaierror:
            if (
                isinstance(host, str)
                and re.fullmatch(r"[a-zA-Z0-9.-]+", host)
                and any(host.endswith(s) for s in LOCALISH_SUFFIXES)
            ):
                return original("127.0.0.1", *args, **kwargs)
            raise

    socket.getaddrinfo = patched


# ─────────────────────────────────────────────────────────────────────────────
# PKCE helpers
# ─────────────────────────────────────────────────────────────────────────────

def b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()


def make_pkce():
    verifier = b64url(secrets.token_bytes(48))
    challenge = b64url(hashlib.sha256(verifier.encode()).digest())
    return verifier, challenge


def authorize_url(disc, client_id, callback, scope="openid profile email"):
    verifier, challenge = make_pkce()
    state, nonce = secrets.token_urlsafe(16), secrets.token_urlsafe(16)
    qs = urlencode(
        {
            "client_id": client_id,
            "redirect_uri": callback,
            "response_type": "code",
            "scope": scope,
            "state": state,
            "nonce": nonce,
            "code_challenge": challenge,
            "code_challenge_method": "S256",
        }
    )
    return f"{disc['authorization_endpoint']}?{qs}", verifier, state, nonce


# ─────────────────────────────────────────────────────────────────────────────
# Seeded machine credentials (docker compose cp from the running zitadel)
# ─────────────────────────────────────────────────────────────────────────────

def fetch_seeded(container_path):
    """Read a seeded credential file from the running zitadel container.

    Tries the overlay set from $COMPOSE_FILE first, then the standard
    demo quartet (scripts/demo.sh), then base + idm — whatever defines a
    `zitadel` service wins. Returns the file content or None.
    """
    sets = []
    if os.environ.get("COMPOSE_FILE"):
        sets.append(os.environ["COMPOSE_FILE"].split(os.pathsep))
    sets.append([
        "docker-compose.yml",
        "idm/zitadel.yml",
        "opencloud/opencloud.yml",
        "profiles/demo.dev.yml",
    ])
    sets.append(["docker-compose.yml", "idm/zitadel.yml"])
    for files in sets:
        cmd = ["docker", "compose"]
        cmd += [arg for f in files for arg in ("-f", f)]
        if (ROOT / ".env").exists():
            cmd += ["--env-file", ".env"]
        cmd += ["cp", f"zitadel:{container_path}", "-"]
        try:
            r = subprocess.run(cmd, cwd=str(ROOT), capture_output=True, timeout=30)
        except Exception:
            continue
        if r.returncode != 0:
            continue
        try:
            tf = tarfile.open(fileobj=io.BytesIO(r.stdout))
            for member in tf.getmembers():
                if member.isfile():
                    return tf.extractfile(member).read().decode().strip()
        except tarfile.TarError:
            continue
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Zitadel Management API (machine PAT) — throw-away OIDC app bootstrap
# ─────────────────────────────────────────────────────────────────────────────

def mgmt(session, idp_base, pat, method, path, payload=None):
    return session.request(
        method,
        idp_base + path,
        json=payload if payload is not None else None,
        headers={"Authorization": f"Bearer {pat}"},
        timeout=T,
    )


def bootstrap_app(session, idp_base, pat, callback, post_logout):
    """Create (or reuse) a throw-away PKCE OIDC app. Returns (client_id, pid, app_id)."""
    proj_name = "e2e-sso"
    r = mgmt(session, idp_base, pat, "POST", "/management/v1/projects/_search", {})
    if r.status_code != 200:
        raise E2EError(f"project search failed: HTTP {r.status_code}")
    pid = next(
        (p["id"] for p in r.json().get("result", []) if p.get("name") == proj_name), None
    )
    if pid is None:
        r = mgmt(session, idp_base, pat, "POST", "/management/v1/projects",
                 {"name": proj_name})
        if r.status_code != 200:
            raise E2EError(f"project add failed: HTTP {r.status_code} {r.text[:120]}")
        pid = r.json().get("id")
    else:
        # Leftover from a crashed earlier run: remove stale apps so app-add
        # can't 409 (an old app's client id would also mismatch our PKCE
        # callback, and its secret is unrecoverable).
        r = mgmt(session, idp_base, pat, "POST",
                 f"/management/v1/projects/{pid}/apps/_search", {})
        if r.status_code == 200:
            for app in r.json().get("result", []):
                if app.get("name") == "e2e-sso":
                    mgmt(session, idp_base, pat, "DELETE",
                         f"/management/v1/projects/{pid}/apps/{app['id']}")
    body = {
        "name": "e2e-sso",
        "redirectUris": [callback],
        "postLogoutRedirectUris": [post_logout],
        "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
        "grantTypes": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
        "appType": "OIDC_APP_TYPE_WEB",
        "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",  # public client, PKCE only
        "devMode": True,  # relax redirect-uri scheme checks (local domains)
    }
    r = mgmt(session, idp_base, pat, "POST",
             f"/management/v1/projects/{pid}/apps/oidc", body)
    if r.status_code != 200:
        raise E2EError(f"oidc app add failed: HTTP {r.status_code} {r.text[:120]}")
    data = r.json()
    return data.get("clientId"), pid, data.get("appId")


def cleanup_app(session, idp_base, pat, pid, app_id):
    if app_id:
        mgmt(session, idp_base, pat, "DELETE",
             f"/management/v1/projects/{pid}/apps/{app_id}")
    if pid:
        mgmt(session, idp_base, pat, "DELETE", f"/management/v1/projects/{pid}")


# ─────────────────────────────────────────────────────────────────────────────
# Zitadel v2 Session API — programmatic login (what the Login v2 UI does)
# ─────────────────────────────────────────────────────────────────────────────

def lc_headers(lc_pat, user_id):
    return {
        "Authorization": f"Bearer {lc_pat}",
        "x-zitadel-login-client": user_id,
    }


def resolve_user_id(session, idp_base, auth_value, login_name):
    """Find the userId for a login name (Management API user search; the
    v2 _by_login_name endpoint 404s until the login_names projection is
    fully warm). Matches machine users (bare name) and human users
    (org-domain suffixed name)."""
    r = session.post(
        f"{idp_base}/management/v1/users/_search",
        json={"userName": login_name.split("@")[0]},
        headers={"Authorization": f"Bearer {auth_value}"},
        timeout=T,
    )
    if r.status_code != 200:
        return None
    stem = login_name.split("@")[0].lower()
    for u in r.json().get("result", []):
        if str(u.get("userName", "")).lower().split("@")[0] == stem:
            return str(u.get("id"))
    return None


def api_login(session, idp_base, lc_pat, client_uid, authz_url, user_id, pw):
    """Log a user in via the v2 Session API and finalize the OIDC auth request.

    Returns (callback_query: dict, session: {id, token}).
    Raises E2EError on any non-2xx step.
    """
    h = lc_headers(lc_pat, client_uid)

    # (a) probe the authorize endpoint — expect a redirect to the login UI
    #     carrying the auth request id (do NOT follow it)
    r = session.get(authz_url, headers=h, allow_redirects=False, timeout=T)
    if r.status_code not in REDIRECTS or "Location" not in r.headers:
        raise E2EError(f"authorize probe: HTTP {r.status_code} {r.text[:80]}")
    m = re.search(r"authRequest=([A-Za-z0-9_:-]+)", r.headers["Location"])
    if not m:
        raise E2EError("authorize did not hand out an auth request id")
    req_id = m.group(1)

    # (b) create a session with the user check
    r = session.post(
        f"{idp_base}/v2/sessions",
        json={"checks": {"user": {"userId": user_id}}},
        headers=h, timeout=T,
    )
    if r.status_code >= 300:
        raise E2EError(f"session create: HTTP {r.status_code} {r.text[:80]}")
    j = r.json()
    sid, stok = j.get("sessionId"), j.get("sessionToken")
    if not sid or not stok:
        raise E2EError("session create returned no id/token")

    # (c) password check (returns the current session token)
    r = session.patch(
        f"{idp_base}/v2/sessions/{sid}",
        json={"checks": {"password": {"password": pw}}},
        headers=h, timeout=T,
    )
    if r.status_code >= 300:
        raise E2EError(
            f"password check: HTTP {r.status_code} "
            f"(wrong E2E_ZITADEL_LOGIN_NAME / ZITADEL_ADMIN_PASSWORD?)"
        )
    stok = r.json().get("sessionToken") or stok

    # (d) finalize the auth request with the session → callback URL
    qs = finalize(session, idp_base, lc_pat, client_uid, req_id, sid, stok)
    return qs, {"id": sid, "token": stok, "req": req_id}


def finalize(session, idp_base, lc_pat, client_uid, req_id, sid, stok):
    """Attach a session to an auth request; returns the callback query params."""
    r = session.post(
        f"{idp_base}/v2/oidc/auth_requests/{req_id}",
        json={"session": {"sessionId": sid, "sessionToken": stok}},
        headers=lc_headers(lc_pat, client_uid), timeout=T,
    )
    if r.status_code >= 300:
        raise E2EError(f"finalize auth request: HTTP {r.status_code} {r.text[:80]}")
    cb = r.json().get("callbackUrl", "")
    qs = parse_qs(urlparse(cb).query)
    if "code" not in qs:
        raise E2EError(f"callback without code: {sorted(qs)}")
    return qs


def terminate(session, idp_base, lc_pat, client_uid, sid, stok):
    """Terminate an IdP session (DELETE /v2/sessions/{id}, token in body)."""
    r = session.delete(
        f"{idp_base}/v2/sessions/{sid}",
        json={"sessionToken": stok},
        headers=lc_headers(lc_pat, client_uid), timeout=T,
    )
    return r.status_code < 300


# ─────────────────────────────────────────────────────────────────────────────
# Sections
# ─────────────────────────────────────────────────────────────────────────────

def probe(session, url) -> bool:
    try:
        session.get(url, timeout=5, allow_redirects=True)
        return True
    except requests.RequestException:
        return False


def section_discovery(result, session, idp_base):
    try:
        r = session.get(f"{idp_base}/.well-known/openid-configuration", timeout=T)
    except requests.RequestException as e:
        result.fail(f"IdP discovery unreachable: {e.__class__.__name__}")
        return None
    if r.status_code != 200:
        result.fail(f"openid-configuration: HTTP {r.status_code}")
        return None
    disc = r.json()
    missing = [
        k for k in ("issuer", "authorization_endpoint", "token_endpoint", "jwks_uri")
        if not disc.get(k)
    ]
    if missing:
        result.fail(f"discovery missing keys: {missing}")
        return None
    result.ok(f"OIDC discovery ok (issuer {disc['issuer']})")

    issuer_host = urlparse(disc["issuer"]).netloc
    if issuer_host and issuer_host != urlparse(idp_base).netloc:
        result.warn(f"issuer host {issuer_host} != configured host")
    try:
        jwks = session.get(disc["jwks_uri"], timeout=T)
        keys = len(jwks.json().get("keys", [])) if jwks.status_code == 200 else 0
        (result.ok if keys else result.fail)(f"JWKS: {keys} key(s)")
    except requests.RequestException:
        result.fail("JWKS unreachable")
    return disc


def section_portal(result, session, portal_base, ai_configured=False):
    try:
        r = session.get(portal_base + "/", timeout=T)
    except requests.RequestException:
        result.skip("portal unreachable")
        return
    if r.status_code != 200:
        result.fail(f"portal /: HTTP {r.status_code}")
    elif "openSME" not in r.text and "opensme" not in r.text.lower():
        result.fail("portal / does not mention openSME")
    else:
        result.ok("portal landing page ok")

    # Trust & transport: plain HTTP must bounce to HTTPS (when served via
    # Traefik; the plain-localhost variant is skipped)
    if portal_base.startswith("https://"):
        try:
            rr = session.get("http://" + portal_base[len("https://"):],
                             allow_redirects=False, timeout=T)
            loc = rr.headers.get("Location", "")
            if rr.status_code in REDIRECTS and loc.startswith("https://"):
                result.ok("plain HTTP redirects to HTTPS")
            else:
                result.fail(f"HTTP did not redirect to HTTPS: "
                            f"{rr.status_code} {loc[:60]}")
        except requests.RequestException as e:
            result.warn(f"HTTP→HTTPS probe failed: {e.__class__.__name__}")

    # Trust in depth: security headers must survive 404s (they guard every
    # response, not just the happy path)
    try:
        miss404 = [
            f"{k}={v}" for k, v in {
                "x-content-type-options": "nosniff",
                "x-frame-options": "DENY",
            }.items() if v not in (session.get(portal_base + "/e2e-not-a-page",
                                               timeout=T).headers.get(k) or "")
        ]
        (result.ok if not miss404 else result.fail)(
            "security headers present on 404 responses" if not miss404
            else f"404 responses lack headers: {'; '.join(miss404)}"
        )
    except requests.RequestException as e:
        result.fail(f"404 header probe failed: {e.__class__.__name__}")

    # security-header contract (must match the middleware in portal/src/main.rs)
    want = {
        "x-content-type-options": "nosniff",
        "x-frame-options": "DENY",
        "referrer-policy": "strict-origin-when-cross-origin",
        "content-security-policy": "default-src 'self'",
    }
    missing = [
        f"{k}={v!r}"
        for k, v in want.items()
        if v not in (r.headers.get(k) or "")
    ]
    (result.ok if not missing else result.fail)(
        "portal security headers ok" if not missing
        else f"portal security headers missing/changed: {'; '.join(missing)}"
    )

    try:
        h = session.get(portal_base + "/health", timeout=T)
        ok = h.status_code == 200 and h.json().get("status") == "ok"
        (result.ok if ok else result.fail)(
            "portal /health ok" if ok else f"portal /health: HTTP {h.status_code} {h.text[:60]}"
        )
        s = session.get(portal_base + "/api/services", timeout=T)
        services = s.json().get("services") if s.status_code == 200 else None
        (result.ok if isinstance(services, list) else result.fail)(
            f"portal /api/services: {len(services)} service(s)" if isinstance(services, list)
            else f"portal /api/services: HTTP {s.status_code}"
        )

        # Truthful catalog: every advertised service must actually answer.
        # The portal must not promise what isn't there.
        if isinstance(services, list):
            dead = []
            for svc in services:
                href = str(svc.get("url") or svc.get("href") or "")
                if not href:
                    dead.append(f"{svc.get('name')!r}: no url")
                    continue
                try:
                    rs = session.get(href, timeout=T, allow_redirects=True)
                    if rs.status_code >= 500:
                        dead.append(f"{svc.get('name')!r}: HTTP {rs.status_code}")
                except requests.RequestException:
                    dead.append(f"{svc.get('name')!r}: unreachable")
            (result.ok if not dead else result.fail)(
                f"all {len(services)} advertised service(s) reachable"
                if not dead else f"catalog lies about: {'; '.join(dead)}"
            )

        # announcements consumer contract: array of {level in info|warn,
        # non-empty text}, capped — this is what app.js renders into HTML
        a = session.get(portal_base + "/api/announcements", timeout=T)
        ann = a.json().get("announcements") if a.status_code == 200 else None
        if not isinstance(ann, list):
            result.fail(f"portal /api/announcements: HTTP {a.status_code}")
        else:
            bad = [
                f"item {i}: level={x.get('level')!r} text={bool(x.get('text', '').strip())}"
                for i, x in enumerate(ann)
                if not isinstance(x, dict)
                or x.get("level") not in ("info", "warn")
                or not str(x.get("text", "")).strip()
            ]
            capped = len(ann) <= 8
            (result.ok if not bad and capped else result.fail)(
                f"portal /api/announcements schema ok ({len(ann)} item(s))"
                if not bad and capped
                else f"portal /api/announcements bad: {'; '.join(bad) or 'cap exceeded'}"
            )

        # AI card gating: the endpoint (and its UI card) must stay hidden
        # unless the operator configured AI_API_URL
        has_card = "id=\"ai-card\"" in r.text
        if has_card == ai_configured:
            result.ok("AI card visibility matches configuration"
                      if has_card else "AI card hidden (AI unconfigured)")
        else:
            result.fail(
                "AI card visible but AI_API_URL unset (must stay hidden)"
                if has_card else "AI_API_URL set but no ai-card rendered"
            )
    except (requests.RequestException, ValueError) as e:
        result.fail(f"portal API: {e.__class__.__name__}")


def run_auth_code_flow(result, session, disc, client_id, csec, idp_base,
                       lc_pat, client_uid, login_name, login_uid, pw, callback):
    """Step 3: full authorization-code + PKCE round trip. Returns id_token + session."""
    authz, verifier, state, nonce = authorize_url(disc, client_id, callback)
    qs, sess = api_login(session, idp_base, lc_pat, client_uid, authz, login_uid, pw)
    if qs.get("state", [None])[0] != state:
        raise E2EError("state mismatch at callback")
    result.ok("login flow produced an authorization code")

    tok = session.post(
        disc["token_endpoint"],
        data={
            "grant_type": "authorization_code",
            "code": qs["code"][0],
            "redirect_uri": callback,
            "client_id": client_id,
            "code_verifier": verifier,
        },
        auth=(client_id, csec) if csec else None,
        timeout=T,
    )
    if tok.status_code != 200:
        raise E2EError(f"token endpoint: HTTP {tok.status_code} {tok.text[:120]}")
    body = tok.json()
    access = body.get("access_token")
    idt = body.get("id_token")
    if not access or not idt:
        raise E2EError("token response missing access/id tokens")
    if len(idt.split(".")) != 3:
        raise E2EError("id_token is not a JWS compact token")
    result.ok("PKCE token exchange ok")

    ui = session.get(
        disc.get("userinfo_endpoint", f"{idp_base}/oidc/v1/userinfo"),
        headers={"Authorization": f"Bearer {access}"},
        timeout=T,
    )
    if ui.status_code != 200:
        raise E2EError(f"userinfo: HTTP {ui.status_code}")
    preferred = ui.json().get("preferred_username", "")
    stem = login_name.split("@")[0]
    if stem.lower() not in str(preferred).lower():
        raise E2EError(f"userinfo subject {preferred!r} does not match {stem!r}")
    result.ok(f"userinfo authenticated as {preferred}")
    return idt, sess, nonce


# ─────────────────────────────────────────────────────────────────────────────
# Journey: issued ID token is a correctly signed, correctly scoped JWT
# ─────────────────────────────────────────────────────────────────────────────

_B64URL = "-_"


def _b64u_int(s: str) -> int:
    return int.from_bytes(
        base64.urlsafe_b64decode(s + "=" * (-len(s) % 4)), "big"
    )


def _b64u_json(s: str) -> dict:
    return json.loads(base64.urlsafe_b64decode(s + "=" * (-len(s) % 4)))


_SHA256_DIGESTINFO = bytes.fromhex("3031300d060960864801650304020105000420")


def _rsa_rs256_verify(jwk: dict, signing_input: bytes, sig: bytes) -> bool:
    """RS256 (RSASSA-PKCS1-v1_5 + SHA-256) verification with pure stdlib:
    s^e mod n must reproduce 00 01 FF..00 || DigestInfo || H(signing_input)."""
    n, e = _b64u_int(jwk["n"]), _b64u_int(jwk["e"])
    k = (n.bit_length() + 7) // 8
    if len(sig) != k:
        return False
    em = pow(_b64u_int(base64.urlsafe_b64encode(sig).decode().rstrip("=")), e, n)
    block = em.to_bytes(k, "big")
    if not block.startswith(b"\x00\x01"):
        return False
    pad_end = block.index(b"\x00", 2)
    if pad_end < 11 or any(b != 0xFF for b in block[2:pad_end]):
        return False
    digest_info = _SHA256_DIGESTINFO + hashlib.sha256(signing_input).digest()
    return block[pad_end + 1:] == digest_info


def verify_id_token(result: Result, session, disc: dict, idt: str,
                    client_id: str, nonce: str) -> None:
    """User story: 'As a relying party, I can trust the issued ID token.'
    Verifies JWS header (RS256 + kid), the RSA signature against the live
    JWKS, and the iss/aud/exp/iat/nonce claims — no extra dependency."""
    try:
        h_b64, p_b64, s_b64 = idt.split(".")
        header = _b64u_json(h_b64)
    except (ValueError, json.JSONDecodeError):
        result.fail("id_token is not a decodable JWS")
        return
    if header.get("alg") != "RS256":
        result.fail(f"id_token alg is {header.get('alg')!r}, expected RS256")
        return
    if not header.get("kid"):
        result.fail("id_token header has no kid")
        return

    try:
        jwks = session.get(disc["jwks_uri"], timeout=T).json()
    except (requests.RequestException, ValueError):
        result.fail("JWKS unreachable for signature verification")
        return
    key = next((k for k in jwks.get("keys", [])
                if k.get("kid") == header["kid"] and k.get("kty") == "RSA"), None)
    if key is None:
        result.fail(f"JWKS has no RSA key for kid {header['kid']!r}")
        return

    sig = base64.urlsafe_b64decode(s_b64 + "=" * (-len(s_b64) % 4))
    if not _rsa_rs256_verify(key, f"{h_b64}.{p_b64}".encode(), sig):
        result.fail("id_token RSA signature does NOT verify against JWKS")
        return
    result.ok("id_token signature verifies against live JWKS (RS256)")

    claims = _b64u_json(p_b64)
    now = int(time.time())
    checks = [
        (claims.get("iss", "").rstrip("/") == disc["issuer"].rstrip("/"),
         f"iss={claims.get('iss')!r} != discovery issuer"),
        (client_id in (claims.get("aud") if isinstance(claims.get("aud"), list)
                       else [claims.get("aud")]),
         f"aud={claims.get('aud')!r} does not include client"),
        (isinstance(claims.get("exp"), int) and claims["exp"] > now,
         "token expired"),
        (isinstance(claims.get("iat"), int) and claims["iat"] <= now + 120,
         f"iat in the future ({claims.get('iat')})"),
        (claims.get("nonce") == nonce, "nonce claim missing/mismatched"),
        (bool(claims.get("sub")), "no subject claim"),
    ]
    bad = [msg for ok, msg in checks if not ok]
    (result.ok if not bad else result.fail)(
        "id_token claims ok (iss/aud/exp/iat/nonce/sub)" if not bad
        else f"id_token claims bad: {'; '.join(bad)}"
    )


def section_sso_reuse(result, session, disc, client_id, callback, idp_base,
                      lc_pat, client_uid, sess):
    """Step 4: a second authorize for the same user is finalized with the
    existing IdP session — no second password check anywhere."""
    authz, _, _, _ = authorize_url(disc, client_id, callback)
    h = lc_headers(lc_pat, client_uid)
    r = session.get(authz, headers=h, allow_redirects=False, timeout=T)
    if r.status_code not in REDIRECTS or "Location" not in r.headers:
        result.fail(f"single sign-on: authorize probe HTTP {r.status_code}")
        return False
    m = re.search(r"authRequest=([A-Za-z0-9_:-]+)", r.headers["Location"])
    if not m:
        result.fail("single sign-on: no auth request id")
        return False
    try:
        finalize(session, idp_base, lc_pat, client_uid, m.group(1), sess["id"], sess["token"])
        result.ok("single sign-on: existing IdP session authorized a second app")
        return True
    except E2EError as e:
        result.fail(f"single sign-on not working: {e}")
        return False


def section_logout(result, session, idp_base, lc_pat, client_uid, sess, client_id, callback, disc):
    """Step 5: terminate the IdP session; a fresh auth request can no longer
    be finalized with the dead session."""
    if not terminate(session, idp_base, lc_pat, client_uid, sess["id"], sess["token"]):
        result.fail("session termination API rejected the request")
        return
    authz, _, _, _ = authorize_url(disc, client_id, callback)
    h = lc_headers(lc_pat, client_uid)
    r = session.get(authz, headers=h, allow_redirects=False, timeout=T)
    m = re.search(r"authRequest=([A-Za-z0-9_:-]+)", r.headers.get("Location", ""))
    if not m:
        result.warn("logout check: could not open a fresh auth request")
        return
    try:
        finalize(session, idp_base, lc_pat, client_uid, m.group(1), sess["id"], sess["token"])
        result.fail("logout ineffective: dead session still finalizes auth requests")
    except E2EError:
        result.ok("logout: terminated session rejected by the IdP")


def section_apps(result, session, urls):
    for label, url in urls:
        try:
            r = session.get(url, timeout=T, allow_redirects=False)
            if r.status_code < 500:
                result.ok(f"{label}: HTTP {r.status_code}")
            else:
                result.fail(f"{label}: HTTP {r.status_code}")
        except requests.RequestException:
            result.skip(f"{label} not running")


def section_opencloud(result: Result, session, cloud_base: str, idp_base: str):
    """Files & collaboration: the cloud web app is up, but its contents sit
    behind an auth wall — and the OIDC wiring to the central IdP is probed
    honestly (warn, not fail, when the subset doesn't register the client)."""
    try:
        r = session.get(cloud_base + "/", timeout=T)
    except requests.RequestException:
        result.skip("opencloud not running")
        return
    if r.status_code != 200 or not re.search(r"opencloud|owncloud", r.text, re.I):
        result.fail(f"opencloud web UI broken: HTTP {r.status_code}")
        return
    result.ok("opencloud web UI loads")

    # files must not be world-readable: unauthenticated WebDAV is denied
    try:
        dav = session.get(cloud_base + "/remote.php/dav/", timeout=T)
        (result.ok if dav.status_code in (401, 403) else result.fail)(
            "WebDAV auth wall holds (401/403)" if dav.status_code in (401, 403)
            else f"WebDAV answers {dav.status_code} without credentials!"
        )
    except requests.RequestException as e:
        result.fail(f"WebDAV probe failed: {e.__class__.__name__}")

    # OIDC wiring: the IdP must know the cloud's client, otherwise login is
    # a dead end (UI loads, auth fails). Diagnostic warn — the minimal demo
    # subset may legitimately ship without the client registration.
    try:
        disc = session.get(idp_base + "/.well-known/openid-configuration",
                           timeout=T).json()
        az = session.get(disc["authorization_endpoint"], params={
            "client_id": "opencloud", "response_type": "code",
            "scope": "openid", "nonce": "e2e-wiring-probe",
            "redirect_uri": f"{cloud_base}/oidc-callback.html",
        }, allow_redirects=False, timeout=T)
        if az.status_code in REDIRECTS:
            result.ok("opencloud OIDC client is registered at the IdP")
        elif "App.NotFound" in az.text or "client" in az.text.lower():
            result.warn("opencloud OIDC client NOT registered in this subset "
                        "— web login would fail (register it for full demo)")
        else:
            result.warn(f"opencloud OIDC probe: HTTP {az.status_code} {az.text[:80]}")
    except (requests.RequestException, ValueError) as e:
        result.warn(f"opencloud OIDC probe failed: {e.__class__.__name__}")


def section_sogo_sso(result, session, webmail_base, idp_base):
    """Groupware journey: opening the webmail app must land on the central
    SSO (same contract as the synapse check)."""
    for path in ("/sogo/", "/"):
        try:
            r = session.get(webmail_base + path, allow_redirects=False, timeout=T)
        except requests.RequestException:
            result.skip("sogo not running")
            return
        if r.status_code == 404:
            continue  # wrong path — try root
        loc = r.headers.get("Location", "")
        if r.status_code in REDIRECTS and loc.startswith(idp_base):
            result.ok("sogo SSO redirect targets the IdP")
            return
        if r.status_code == 200:
            result.warn("sogo reachable but serves a local login (SSO not enforced)")
            return
        result.warn(f"sogo probe: HTTP {r.status_code} {loc[:60]}")
        return
    result.skip("sogo not running")


def section_user_lifecycle(result: Result, session, disc: dict, client_id: str,
                           callback: str, idp_base: str, lc_pat: str,
                           client_uid: str, pat: str):
    """Identity lifecycle: an operator provisions a user via API, that user
    logs in through the full SSO flow, and after deletion the dead identity
    is rejected. Leftovers from crashed runs are purged first."""
    H = {"Authorization": f"Bearer {pat}", "Content-Type": "application/json"}
    uname = "e2e-throwaway"

    # 0) purge leftovers (crashed previous runs) — the journey must be idempotent
    lst = session.post(idp_base + "/v2/users", headers=H, json={"queries": [
        {"userNameQuery": {"userName": uname, "method": "TEXT_QUERY_METHOD_EQUALS"}}
    ]}, timeout=T).json()
    for stale in (lst.get("result") or []):
        session.delete(idp_base + f"/v2/users/{stale.get('userId')}",
                       headers=H, timeout=T)
    if lst.get("result"):
        result.ok("purged leftover identity from a previous run")

    # 1) provision: create the user WITH their initial password (the admin
    #    path; the separate /password endpoint is self-service and needs
    #    verification)
    pw = "E2e-" + secrets.token_urlsafe(9) + "!7"
    j = session.post(idp_base + "/v2/users/human", headers=H, json={
        "username": uname,
        "profile": {"givenName": "E2", "familyName": "Throwaway"},
        "email": {"email": f"{uname}@e2e.invalid", "isVerified": True},
        "password": {"password": pw, "changeRequired": False},
    }, timeout=T).json()
    uid = j.get("userId", "")
    if not uid:
        result.fail(f"user provisioning failed: {str(j)[:100]}")
        return
    result.ok(f"provisioned identity {uname} ({uid})")

    try:
        # 2) that user logs in through the full authorization-code flow
        authz, verifier, state, nonce = authorize_url(disc, client_id, callback)
        qs, _sess = api_login(session, idp_base, lc_pat, client_uid, authz,
                              uid, pw)
        if qs.get("code"):
            result.ok("freshly provisioned user completes the SSO flow")
        else:
            result.fail("provisioned user login produced no code")

        # 3) deletion → the dead identity must be rejected while the app is
        #    still alive (isolate the user-lifecycle assertion)
        r = session.delete(idp_base + f"/v2/users/{uid}", headers=H, timeout=T)
        if r.status_code >= 300:
            result.fail(f"user deletion failed: HTTP {r.status_code}")
            return
        result.ok("deleted identity")
        try:
            api_login(session, idp_base, lc_pat, client_uid, authz, uid, pw)
            result.fail("deleted identity was still able to log in")
        except E2EError:
            result.ok("deleted identity is rejected by the IdP")
    finally:
        session.delete(idp_base + f"/v2/users/{uid}", headers=H, timeout=T)


def section_synapse_sso(result, session, matrix_base, idp_base):
    url = f"{matrix_base}/_matrix/client/v3/login/sso/redirect"
    try:
        r = session.get(
            url, params={"redirectUrl": matrix_base + "/"},
            allow_redirects=False, timeout=T,
        )
    except requests.RequestException:
        result.skip("synapse not running")
        return
    if r.status_code == 404:
        result.skip("synapse SSO not enabled (no OIDC provider wired)")
        return
    loc = r.headers.get("Location", "")
    if r.status_code in REDIRECTS and loc.startswith(idp_base):
        result.ok("synapse SSO redirect targets the IdP")
    elif r.status_code in REDIRECTS:
        result.fail(f"synapse SSO redirects to {loc[:80]} (expected the IdP)")
    else:
        result.warn(f"synapse SSO probe: HTTP {r.status_code}")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> bool:
    global VERIFY
    ap = argparse.ArgumentParser(description="openSME e2e tests (SSO etc.)")
    ap.add_argument("domain", nargs="?", default=None, help="stack domain")
    ap.add_argument("--insecure", action="store_true", help="disable TLS verification")
    ap.add_argument("--map-local", action="store_true",
                    help="resolve unresolvable *.local hosts to loopback")
    ap.add_argument("--skip-flows", action="store_true", help="skip SSO flow tests")
    ap.add_argument("--skip-apps", action="store_true", help="skip app reachability")
    ap.add_argument("--idp-url", default=None, help="override IdP base URL")
    args = ap.parse_args()

    dotenv = load_env_file()

    def cfg(key, default=""):
        return os.environ.get(key) or dotenv.get(key) or default

    domain = (args.domain or cfg("OPENSME_DOMAIN", "localhost")).strip()
    localish = is_localish(domain)
    VERIFY = not (args.insecure or cfg("E2E_INSECURE") in ("1", "true", "yes") or localish)
    if not VERIFY:
        urllib3.disable_warnings()
    if localish or args.map_local:
        install_dns_fallback()

    idp_host = cfg("ZITADEL_DOMAIN", f"auth.{domain}")
    idp_base = args.idp_url or f"https://{idp_host}"
    portal_base = (
        "http://127.0.0.1:8080" if domain in ("localhost", "127.0.0.1")
        else f"https://{cfg('PORTAL_DOMAIN', f'portal.{domain}')}"
    )
    cloud_base = f"https://{cfg('OPENCLOUD_DOMAIN', f'cloud.{domain}')}"
    webmail_base = f"https://{cfg('SOGO_DOMAIN', f'webmail.{domain}')}"
    matrix_base = f"https://matrix.{domain}"
    notes_base = f"https://notes.{domain}"
    paperless_base = f"https://paperless.{domain}"
    help_base = f"https://help.{domain}"
    www_base = f"https://www.{domain}"
    shop_base = f"https://shop.{domain}"

    session = requests.Session()
    session.verify = VERIFY

    result = Result("e2e")
    result.header(f"openSME e2e — domain={domain} idp={idp_base} verify={VERIFY}")

    if not probe(session, idp_base + "/debug/ready") and not probe(session, portal_base + "/health"):
        result.fail("stack unreachable — start it first (./scripts/demo.sh or make up)")
        return result.summary()

    # 1) IdP discovery
    disc = section_discovery(result, session, idp_base)

    # 2) Portal (AI card gating depends on AI_API_URL configuration)
    section_portal(result, session, portal_base, ai_configured=bool(cfg("AI_API_URL")))

    # 3-5) SSO flows
    flows_ok = bool(disc) and not args.skip_flows
    client_id, csec, owned, pat = cfg("E2E_OIDC_CLIENT_ID"), cfg("E2E_OIDC_CLIENT_SECRET"), None, None
    callback, post_logout = f"{idp_base}/e2e-callback", f"{idp_base}/e2e-loggedout"
    login_name = cfg("E2E_ZITADEL_LOGIN_NAME", "zitadel-admin")
    pw = cfg("ZITADEL_ADMIN_PASSWORD")

    lc_pat = cfg("E2E_ZITADEL_LOGINCLIENT_PAT")
    client_uid = None

    if flows_ok and not client_id:
        pat = cfg("E2E_ZITADEL_PAT") or fetch_seeded("/machinekey/pat")
        if not pat:
            result.skip("SSO flows: no machine PAT reachable (docker compose down?) — "
                        "set E2E_OIDC_CLIENT_ID or E2E_ZITADEL_PAT")
            flows_ok = False
        else:
            try:
                client_id, pid, app_id = bootstrap_app(session, idp_base, pat, callback, post_logout)
                owned = (pid, app_id)
                result.ok(f"bootstrapped throw-away OIDC app (client {client_id})")
            except E2EError as e:
                result.skip(f"SSO flows skipped — OIDC app bootstrap failed: {e}")
                flows_ok = False

    if flows_ok:
        lc_pat = lc_pat or fetch_seeded("/machinekey/login-client.pat")
        client_uid = resolve_user_id(session, idp_base, pat or lc_pat, LOGIN_CLIENT_USER) \
            if lc_pat else None
        if not lc_pat or not client_uid:
            result.skip("SSO flows: no login-client PAT (re-run `zitadel setup --steps "
                        "/steps.yaml` on a fresh DB) or set E2E_ZITADEL_LOGINCLIENT_PAT")
            flows_ok = False

    login_uid = None
    if flows_ok:
        login_uid = resolve_user_id(session, idp_base, pat or lc_pat, login_name)
        if not login_uid:
            result.fail(f"auth-code flow: login user {login_name!r} not found in IdP")
            flows_ok = False

    if flows_ok and not pw:
        result.skip("SSO flows: no admin credentials (set ZITADEL_ADMIN_PASSWORD)")
        flows_ok = False

    sess = None
    idt = nonce = None
    if flows_ok:
        try:
            idt, sess, nonce = run_auth_code_flow(
                result, session, disc, client_id, csec, idp_base,
                lc_pat, client_uid, login_name, login_uid, pw, callback,
            )
        except E2EError as e:
            result.fail(f"auth-code flow: {e}")
            flows_ok = False

    if flows_ok and idt:
        verify_id_token(result, session, disc, idt, client_id, nonce)

    if flows_ok and sess:
        if section_sso_reuse(result, session, disc, client_id, callback, idp_base,
                             lc_pat, client_uid, sess):
            section_logout(result, session, idp_base, lc_pat, client_uid, sess,
                           client_id, callback, disc)

    # Identity lifecycle (provision → SSO login → delete → dead login
    # rejected) — reuses the throw-away app while it is still alive
    if flows_ok and disc and client_id and lc_pat and client_uid and pat:
        try:
            section_user_lifecycle(result, session, disc, client_id, callback,
                                   idp_base, lc_pat, client_uid, pat)
        except E2EError as e:
            result.fail(f"identity lifecycle: {e}")

    # Cleanup the throw-away app (best effort)
    if owned and pat:
        try:
            cleanup_app(session, idp_base, pat, owned[0], owned[1])
            result.ok("removed throw-away OIDC app")
        except Exception:
            result.warn("could not remove throw-away OIDC app (delete project 'e2e-sso')")

    # 6) App reachability
    if not args.skip_apps:
        section_apps(result, session, [
            ("opencloud", cloud_base + "/"),
            ("synapse", matrix_base + "/_matrix/client/versions"),
            ("notes", notes_base + "/"),
            ("paperless", paperless_base + "/"),
            ("ticketing", help_base + "/"),
            ("cms", www_base + "/"),
            ("store", shop_base + "/"),
            ("webmail", webmail_base + "/sogo/"),
        ])

    # 7) Synapse + SOGo SSO wiring
    if not args.skip_apps:
        section_synapse_sso(result, session, matrix_base, idp_base)
        section_sogo_sso(result, session, webmail_base, idp_base)

    # 8) Files & collaboration — auth wall + OIDC wiring of the cloud
    if not args.skip_apps:
        section_opencloud(result, session, cloud_base, idp_base)

    return result.summary()


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
